catalogMode: prefer

# 是否忽略向工作区根目录添加依赖时的警告提示
ignoreWorkspaceRootCheck: true

registry: https://registry.npmmirror.com

# 是否强制提升所有依赖
shamefullyHoist: true

# 在执行脚本时使用POSIX shell模拟器替代系统原生shell
shellEmulator: true

# 用于控制是否严格检查对等依赖（peer dependencies）的版本一致性。
# 当设置为 true 时，pnpm 会强制安装指定版本的对等依赖；
# 设置为 false 时，会忽略版本不一致的警告
strictPeerDependencies: false

catalogs:
  dev:
    '@lincy/polyfill-useragent-normaliser': ^1.10.2
    '@lincy/unocss-base-config': ^2.4.2
    '@mrhenry/polyfill-library': ^5.2.1
    '@unocss/eslint-plugin': ^66.6.0
    '@vitejs/plugin-vue': ^6.0.3
    '@vitejs/plugin-vue-jsx': ^5.1.3
    '@vue-macros/define-props': ^3.1.2
    '@vue-macros/define-props-refs': ^3.1.2
    '@vue-macros/reactivity-transform': ^3.1.2
    '@vue-macros/volar': ^3.1.2
    cross-env: ^10.1.0
    jiti: ^2.6.1
    mockjs: ^1.1.0
    nitro: ^3.0.1-alpha.2
    sass: ^1.97.3
    typescript: ~5.9.3
    unocss: ^66.6.0
    unplugin-auto-import: ^21.0.0
    unplugin-icons: ^23.0.1
    unplugin-vue-components: ^31.0.0
    vite: ^7.3.1
    vite-plugin-inspect: ^11.3.3
    vite-plugin-progress: ^0.0.7
    vue-macros: ^3.1.2
    vue-tsc: ^3.2.4

  icons:
    '@element-plus/icons-vue': ^2.3.2
    '@iconify-json/carbon': ^1.2.18
    '@iconify-json/fad': ^1.2.1
    '@iconify-json/svg-spinners': ^1.2.4
    '@iconify-json/vscode-icons': ^1.2.40

  lint:
    '@lincy/eslint-config': ^6.4.0
    '@lincy/stylelint-config': ^2.2.1
    eslint: ^9.39.2
    eslint-plugin-format: ^1.3.1

  prod:
    '@lincy/async-validation': ^1.4.0
    '@lincy/utils': ^0.7.3
    '@tanstack/vue-query': ^5.92.9
    '@tato30/vue-pdf': ^1.11.5
    '@unhead/vue': ^2.1.2
    '@unocss/reset': ^66.6.0
    '@vueuse/core': ^14.1.0
    '@vueuse/router': ^14.1.0
    alova: ^3.5.0
    better-sqlite3: ^12.6.2
    default-passive-events: ^4.0.0
    destr: ^2.0.5
    element-plus: ^2.13.1
    highlight.js: ^11.11.1
    lodash: ^4.17.23
    markdown-it-link-attributes: ^4.0.1
    md-editor-v3: ^6.3.1
    mitt: ^3.0.1
    ofetch: ^1.5.1
    pinia: ^3.0.4
    qs: ^6.14.1
    store2: ^2.14.4
    twig: ^1.17.1
    vue: ^3.5.27
    vue-router: ^4.6.4

  types:
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/mockjs': ^1.0.10
    '@types/node': ^25.1.0
    '@types/qs': ^6.14.0
    '@types/twig': ^1.12.17

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - vue-demi
