catalogMode: prefer

# 是否忽略向工作区根目录添加依赖时的警告提示
ignoreWorkspaceRootCheck: true

# npm 包注册表的基本 URL（包括尾部斜杠）
registry: https://registry.npmmirror.com/
registries:
  default: https://registry.npmmirror.com/

# 定义了版本发布后 pnpm 安装之前必须经过的最少分钟数
minimumReleaseAge: 0

# 是否强制提升所有依赖
shamefullyHoist: true

# 在执行脚本时使用POSIX shell模拟器替代系统原生shell
shellEmulator: true

# 用于控制是否严格检查对等依赖（peer dependencies）的版本一致性。
# 当设置为 true 时，pnpm 会强制安装指定版本的对等依赖；
# 设置为 false 时，会忽略版本不一致的警告
strictPeerDependencies: false

# 当设置为“禁止降级”时，如果软件包的信任级别较之前的版本有所降低，pnpm 将无法安装
trustPolicy: no-downgrade

# 列出一个或多个 pnpm 应该允许安装的特定软件包或版本，即使这些软件包不满足信任策略要求。
trustPolicyExclude:
  - semver
  - chokidar
  - cached-factory

catalogs:
  dev:
    '@lincy/polyfill-useragent-normaliser': ^1.10.2
    '@lincy/unocss-base-config': ^2.7.3
    '@mrhenry/polyfill-library': ^5.2.1
    '@unocss/eslint-plugin': ^66.7.0
    '@vitejs/plugin-vue': ^6.0.7
    '@vitejs/plugin-vue-jsx': ^5.1.5
    '@vue-macros/define-props': ^3.1.2
    '@vue-macros/define-props-refs': ^3.1.2
    '@vue-macros/reactivity-transform': ^3.1.2
    '@vue-macros/volar': ^3.1.2
    baseline-browser-mapping: ^2.10.35
    cross-env: ^10.1.0
    jiti: ^2.7.0
    mockjs: ^1.1.0
    nitro: ^3.0.260610-beta
    sass-embedded: ^1.100.0
    typescript: ~6.0.3
    unocss: ^66.7.0
    unplugin-auto-import: ^21.0.0
    unplugin-icons: ^23.0.1
    unplugin-vue-components: ^32.1.0
    vite: ^8.0.16
    vite-plugin-inspect: ^12.0.0-beta.3
    vite-plugin-progress: ^0.0.7
    vue-macros: ^3.1.2
    vue-tsc: ^3.3.4

  icons:
    '@element-plus/icons-vue': ^2.3.2
    '@iconify-json/carbon': ^1.2.23
    '@iconify-json/fad': ^1.2.1
    '@iconify-json/svg-spinners': ^1.2.4
    '@iconify-json/vscode-icons': ^1.2.55

  lint:
    '@lincy/eslint-config': ^7.2.0
    '@lincy/stylelint-config': ^2.2.3
    eslint: ^10.4.1
    eslint-plugin-format: ^2.0.1
    stylelint: ^17.13.0

  prod:
    '@lincy/async-validation': ^1.4.0
    '@lincy/utils': ^0.7.3
    '@unhead/vue': ^3.1.3
    '@unocss/reset': ^66.7.0
    '@vueuse/core': ^14.3.0
    '@vueuse/router': ^14.3.0
    bcryptjs: ^3.0.3
    better-sqlite3: ^12.10.0
    default-passive-events: ^4.0.0
    destr: ^2.0.5
    dompurify: ^3.4.9
    drizzle-kit: ^0.31.10
    drizzle-orm: ^0.45.2
    element-plus: ^2.14.1
    highlight.js: ^11.11.1
    jose: ^6.2.3
    lodash: ^4.18.1
    markdown-it-link-attributes: ^4.0.1
    md-editor-v3: ^6.5.1
    ofetch: ^1.5.1
    pinia: ^3.0.4
    qs: ^6.15.2
    store2: ^2.14.4
    twig: ^3.0.0
    vue: ^3.5.35
    vue-router: ^5.1.0

  types:
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/mockjs': ^1.0.10
    '@types/node': ^25.9.3
    '@types/qs': ^6.15.1
    '@types/twig': ^1.12.17

peerDependencyRules:
  ignoreMissing:
    - sass

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  vue-demi: true
