/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleDialogPost: typeof import('./components/article/dialog-post.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    EmptyComponents: typeof import('./components/empty-components.vue')['default']
    GlobalDialog: typeof import('./components/global/dialog.vue')['default']
    GlobalDigital: typeof import('./components/global/digital.tsx')['default']
    GlobalFooter: typeof import('./components/global/footer.vue')['default']
    GlobalHeader: typeof import('./components/global/header.vue')['default']
    HomeCategory: typeof import('./components/home/category.vue')['default']
    HomeRecommend: typeof import('./components/home/recommend.vue')['default']
    NewsRecommend: typeof import('./components/news/recommend.vue')['default']
    OtherCommentPost: typeof import('./components/other/comment-post.vue')['default']
    OtherComments: typeof import('./components/other/comments.vue')['default']
    OtherLoading: typeof import('./components/other/loading.vue')['default']
    OtherRelatedRecom: typeof import('./components/other/related-recom.vue')['default']
    OtherTopBanner: typeof import('./components/other/top-banner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const ArticleDialogPost: typeof import('./components/article/dialog-post.vue')['default']
  const ElAffix: typeof import('element-plus/es')['ElAffix']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
  const ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
  const EmptyComponents: typeof import('./components/empty-components.vue')['default']
  const GlobalDialog: typeof import('./components/global/dialog.vue')['default']
  const GlobalDigital: typeof import('./components/global/digital.tsx')['default']
  const GlobalFooter: typeof import('./components/global/footer.vue')['default']
  const GlobalHeader: typeof import('./components/global/header.vue')['default']
  const HomeCategory: typeof import('./components/home/category.vue')['default']
  const HomeRecommend: typeof import('./components/home/recommend.vue')['default']
  const NewsRecommend: typeof import('./components/news/recommend.vue')['default']
  const OtherCommentPost: typeof import('./components/other/comment-post.vue')['default']
  const OtherComments: typeof import('./components/other/comments.vue')['default']
  const OtherLoading: typeof import('./components/other/loading.vue')['default']
  const OtherRelatedRecom: typeof import('./components/other/related-recom.vue')['default']
  const OtherTopBanner: typeof import('./components/other/top-banner.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}